### PR TITLE
Adjustments responsive design

### PR DESCRIPTION
**Pull request by mattreim**
DTU

### CODE REVIEW

**Comment by mattreim** [comment]
Now:

DTU

**Comment by simatec** [comment]
Unfortunately, the changes are not correct. As the current jsonConfig is structured, everything is correct and no changes are required for a responsive design on smaller screens

**Comment by mattreim** [comment]
Changed

**Comment by simatec** [comment]
thx

**Comment by mcm1957** [comment]
fixed 3.1.0

**Pull request merged**
